substitutions:
  name: "waveshare_172x320"
  friendly_name: Waveshare 172x320

  Outlines: "0" # Setting to 0 will disable all Outlines
#---------------------------------------------------------------------------------------------------
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.9.0
  name_add_mac_suffix: false
  project:
    name: esphome.${name}
    version: '1.0'
  on_boot: 
    priority: -100
    then:
      - light.turn_on: 
          id: backlight
          brightness: 75%
#---------------------------------------------------------------------------------------------------
esp32:
  variant: esp32c6
  framework:
    type: esp-idf
#---------------------------------------------------------------------------------------------------
# Enable logging
logger:
#---------------------------------------------------------------------------------------------------
# Enable Home Assistant API
api:
  encryption: 
    key: !secret haapi_key
#---------------------------------------------------------------------------------------------------
# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password
#---------------------------------------------------------------------------------------------------
wifi:
  min_auth_mode: wpa2
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: off
#---------------------------------------------------------------------------------------------------
time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
    - lvgl.label.update:
        id: display_time
        text: !lambda return id(HATime).state;
    - lvgl.label.update:
        id: display_date
        text: !lambda return id(HADate).state;
#---------------------------------------------------------------------------------------------------
spi:
  - id: lcd
    clk_pin:
      number: GPIO7
    mosi_pin:
      number: GPIO6
#---------------------------------------------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
      update_interval: 1h
    ssid:
      name: ${friendly_name} SSID
      update_interval: 1h
    mac_address:
      name: ${friendly_name} Mac
#--------------------------------------
  - platform: homeassistant
    id: HATime
    entity_id: sensor.time
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_time
          text: !lambda return id(HATime).state;
#--------------------------------------
  - platform: homeassistant
    id: HADate
    entity_id: sensor.date
    device_class: timestamp
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_date
          text: !lambda return id(HADate).state;
#---------------------------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "${friendly_name} Restart"
#---------------------------------------------------------------------------------------------------
# Backlight control
output:
  - platform: ledc
    pin: GPIO22
    id: backlight_output
    frequency: 5000 Hz
#---------------------------------------------------------------------------------------------------
light:
  - platform: monochromatic
    output: backlight_output
    id: backlight
    name: "LCD Backlight"
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 1s
#---------------------------------------------------------------------------------------------------
display:
  - platform: ili9xxx
    id: ws_display
    model: ST7789V
    spi_id: lcd
    color_palette: 8BIT
    cs_pin: 
      number: GPIO14
    dc_pin: 
      number: GPIO15
      ignore_strapping_warning: true
    reset_pin: 
      number: GPIO21
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false
    show_test_card: False
    dimensions: 
      height: 172 #Landscape
      width: 320 #Landscape
      offset_width: 0 #Landscape
      offset_height: 34 #Landscape
#      height: 320 #Portrait
#      width: 172 #Portrait
#      offset_width: 34 #Portrait
#      offset_height: 0 #Portrait
    transform: 
      mirror_x: False #Landscape
      mirror_y: True #Landscape
      swap_xy: True #Landscape
#      mirror_x: False #Portrait
#      mirror_y: False #Portrait
#      swap_xy: False #Portrait
#---------------------------------------------------------------------------------------------------
lvgl:
  displays:
    - ws_display
#--------------------------------------
  style_definitions:
    - id: mystyle
      text_font: concert_48
      text_color: 0x2F8CD8
      bg_color: 0x000000
      grid_cell_x_align: Stretch
      grid_cell_y_align: CENTER
      align: CENTER
      text_align: CENTER
#--------------------------------------
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        - obj:
            align: CENTER
            height: 167 #Landscape
            width: 315 #Landscape
#            height: 320 #Portrait
#            width: 172 #Portrait
            bg_opa: TRANSP
            border_opa: TRANSP
            outline_width: ${Outlines}
            outline_color: 0xFF0000
            pad_all: 0
            x: 0
            y: 0
            layout:
              type: grid
              grid_columns: [FR(1)]
              grid_rows: [FR(1),FR(1)]
            widgets:
              - label:
                  id: display_time
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  text: "--:--"
                  styles: mystyle
                  outline_width: ${Outlines}
                  outline_color: 0x00FF00
              - label:
                  id: display_date
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  text: "----/--/--"
                  styles: mystyle
                  outline_width: ${Outlines}
                  outline_color: 0x00FF00
#---------------------------------------------------------------------------------------------------
font:
  - file: "gfonts://Concert One"
    id: concert_48
    size: 48
    bpp: 4
#-------------------------------------------------------

#---------------------------------------------------------------------------------------------------
